### ISSUE TITLE
Implement downlink

### ISSUE THREAD

**Issue by adrien3d** [adrien3d/IO_WSSFM10-Arduino#1]
Implement downlink in addition to the uplink that is already done.

**Comment by nimasaj** [comment]
I agree that it would be really helpful to have an example with downlink as well.

**Comment by adrien3d** [comment]
This was done in https://github.com/adrien3d/IO_WSSFM10-Arduino/commit/38047eb1bb3ceea70e6bd3ca94ed41487517d485 and https://github.com/adrien3d/IO_WSSFM10-Arduino/commit/0cc1ec43c47342cec3709fa765639a95b653f7c4
