### ISSUE TITLE
Footprint/Eagle files of WSSFM10R1 or WSSFM11R2D or BRKWS01

### ISSUE THREAD

**Issue by nimasaj** [adrien3d/IO_WSSFM10-Arduino#13]
Is there any footprint for WSSFM10R1 or WSSFM11R2D? Or Eagle files related to breakout board (BRKWS01)?

Since there is no breakout board for WSSFM11R2D on Yadom, I would like to make it myself. Therefore, I would be thankful if you share design (Eagle) files for BRKWS01.

Thanks

**Comment by adrien3d** [comment]
Hi @nimasaj,

You should look [here](https://github.com/SeaSlugLabs/Wisol-WSSFM10R2-Sigfox-Breakout) or [here](https://github.com/lupyuen/Wisol-WSSFM10R-Sigfox-Breakout)

**Comment by nimasaj** [comment]
Thanks Adrien.
