### ISSUE TITLE
Break to wake up from Sleep mode

### ISSUE THREAD

**Issue by nimasaj** [adrien3d/IO_WSSFM10-Arduino#4]
Could you provide an example to wake the module up from sleep mode with a break? 

I just found some explanation in page 11 of following datasheet, but still unclear for me. 

> To wake the AX−Sigfox up from Sleep mode toggle the serial UARTRX pin, e.g. by sending a break (break is an RS232 framing violation, i.e. at least 10 bit durations low). 

`https://www.onsemi.com/pub/Collateral/AX-SIGFOX-D.PDF`

**Comment by adrien3d** [comment]
Yep, this was done in https://github.com/adrien3d/IO_WSSFM10-Arduino/commit/38047eb1bb3ceea70e6bd3ca94ed41487517d485
